#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
COMMIT_MESSAGE_FILE=$1
COMMIT_MESSAGE=$(cat "$COMMIT_MESSAGE_FILE")

COMMIT_PATTERN="^:[a-zA-Z]+: [^\n]+$"

echo "❤️‍🩹 Commit Message: $COMMIT_MESSAGE"

if [[ ! $COMMIT_MESSAGE =~ $COMMIT_PATTERN ]]; then
  echo "💕 you have to use gitmoji "
  exit 1
fi

echo "🔆 Thanks for keeping the convention 🔆"